[package]
name = "sajit"
version = "0.0.6"
edition = "2024"
license = "Apache-2.0"
rust-version = "1.95"

description = "Good Enough JIT Code Slab Allocator, Relocator, Linker interface"
homepage = "https://github.com/savmlang/sajit"
repository = "https://github.com/savmlang/sajit.git"

[dependencies]
object = "^0.40"

[target.'cfg(unix)'.dependencies]
libc = "^0.2"

[target.'cfg(windows)'.dependencies]
windows = { version = "^0.62", features = [
  "Win32_Security",
  "Win32_System_Memory",
  "Win32_System_Threading",
  "Win32_System_Diagnostics_Debug",
  "Win32_Foundation",
  "Win32_System",
  "Win32_System_SystemServices",
] }

[build-dependencies]
bindgen = { version = "^0.73", optional = true }
cc = { version = "^1", optional = true }

[dev-dependencies]
cranelift = { version = "^0.135", features = ["native"] }

[features]
llvm = ["dep:cc", "dep:bindgen"]

[package.metadata.docs.rs]
all-features = true
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",

  "aarch64-unknown-linux-gnu",
  "aarch64-apple-darwin",
  "aarch64-pc-windows-msvc",
]
